name: Portfolio

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subsito/flutter-action@v1
      - uses: bluefireteam/flutter-gh-pages@v7